IMAGE:
  WIDTH: 640
  HEIGHT: 480
  ROI_START_HEIGHT: 375 #340 # 360 -> 355
  ROI_HEIGHT: 40 # 40 # 60 -> 50

XYCAR:
  START_SPEED: 14.0
  MAX_SPEED: 14 # 40
  MIN_SPEED: 6.5 # 15
  SPEED_CONTROL_THRESHOLD: 13 # 15
  ACCELERATION_STEP: 0.025 # 0.05
  DECELERATION_STEP: 0.1 # 0.1

PID:
  P_GAIN: 0.6 #0.36
  I_GAIN: 0.001 #0.0006
  D_GAIN: 0.4 # 0.08

SPEED_PID:
  P_GAIN: 0.4
  I_GAIN: 0.0150
  D_GAIN: 0.005

STANLEY:
  K_GAIN: 0.07 # 0.032
  LOOK_AHREAD_DISTANCE: 0.3 # 0.2

MOVING_AVERAGE_FILTER:
  SAMPLE_SIZE: 60

TOPIC:
  PUB_NAME: /xycar_motor
  SUB_NAME: /usb_cam/image_raw/
  QUEUE_SIZE: 1

CANNY:
  LOW_THRESHOLD: 150
  HIGH_THRESHOLD: 250 #250

HOUGH:
  ABS_SLOPE_RANGE: 10.0
  THRESHOLD: 40
  MIN_LINE_LENGTH: 25 #35
  MAX_LINE_GAP: 20 # 10

DEBUG: False
